version: '3'
services:
  bot:
    build: .
    restart: always
    env_file: .env.development.local
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
